# 注释以井号（#）开头

name: "gpdf"
port: 8081
version: "0.1"
mode: "dev"
machine_id: 1
jwt_key: "UubMLwC+SKs2xvGVgjXLLa0p+x1Q69kN82/U+E/+lSg="

mysql:
  #  host: 172.19.0.3
  host: localhost
  user: gpdf
  password: 123456
  dbname: gpdf
  port: 3306
  max_open_conns: 100
  max_idle_conns: 10
  sslmode: "disable"
  time_zone: "Asia/Shanghai"


# redis不支持windows 使用远程redis服务
redis:
  #  host: 172.19.0.2
  host: 192.168.183.130
  password: ""
  port: 6379
  db: 0
  pool_size: 50
  min_idle_conns: 20
#  connect_type: ""
#  ssh_remote_host: "ipaddr:22"
#  ssh_file: C:\Users\xx\.ssh\id_ed25519

log:
  level: "debug"
  filename: "./log/gpdf.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  local_time: true

etcd:
  host: 192.168.183.130
  port: 5672

server:
  user_srv_address: 127.0.0.1:8082
  pdf_srv_address: 127.0.0.1:8083
